function(recommend_monotonicity BINS R S)
    if (BINS EQUAL 3 AND R EQUAL 45 AND S EQUAL 33)
        set(MONOT 5)
    # 3 bins:
    elseif ((BINS EQUAL 3) AND (R EQUAL 45) AND (S EQUAL 33))
        set(MONOT 5)
    elseif ((BINS EQUAL 3) AND (R EQUAL 72) AND (S EQUAL 53))
        set(MONOT 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 86) AND (S EQUAL 63))
        set(MONOT 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 112) AND (S EQUAL 82))
        set(MONOT 8)
    elseif ((BINS EQUAL 3) AND (R EQUAL 123) AND (S EQUAL 90))
        math(EXPR MONOT "${S}-1")
    elseif ((BINS EQUAL 3) AND (R EQUAL 138) AND (S EQUAL 101))
        set(MONOT 20)
    elseif ((BINS EQUAL 3) AND (R EQUAL 153) AND (S EQUAL 112))
        set(MONOT 8)
    elseif ((BINS EQUAL 3) AND (R EQUAL 164) AND (S EQUAL 120))
        set(MONOT 15)
    elseif ((BINS EQUAL 3) AND (R EQUAL 175) AND (S EQUAL 128))
        set(MONOT 25)
    elseif ((BINS EQUAL 3) AND (R EQUAL 190) AND (S EQUAL 139))
        set(MONOT 25)
    elseif ((BINS EQUAL 3) AND (R EQUAL 194) AND (S EQUAL 142))
        set(MONOT 15)
    elseif ((BINS EQUAL 3) AND (R EQUAL 205) AND (S EQUAL 150))
        set(MONOT 15)
    elseif ((BINS EQUAL 3) AND (R EQUAL 329) AND (S EQUAL 240)) # For some specific configurations.
        set(MONOT 35)
    elseif ((BINS EQUAL 3) AND (R EQUAL 411) AND (S EQUAL 300))
        set(MONOT 15)
        set(SCALE 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 657) AND (S EQUAL 480))
        set(MONOT 60)
    elseif ((BINS EQUAL 3) AND (R EQUAL 821) AND (S EQUAL 600))
        set(MONOT 70)
    elseif ((BINS EQUAL 3) AND (R EQUAL 985) AND (S EQUAL 720))
        set(MONOT 60)
    elseif ((BINS EQUAL 3)) # Default on 3 bins.
        math(EXPR MONOT "${S}-1")
        # 4 bins:
    elseif ((BINS EQUAL 4) AND (R EQUAL 19) AND (S EQUAL 14))
        set(MONOT 2)
    elseif ((BINS EQUAL 4) AND (R EQUAL 112) AND (S EQUAL 82))
        set(MONOT 16)
    elseif ((BINS LESS_EQUAL 7) AND (R EQUAL 19) AND (S EQUAL 14))
        set(MONOT 1)
    elseif ((BINS GREATER_EQUAL 8) AND (BINS LESS_EQUAL 9) AND (R EQUAL 19) AND (S EQUAL 14))
        set(MONOT 1)
    elseif ((BINS GREATER_EQUAL 10) AND (R EQUAL 19) AND (S EQUAL 14))
        set(MONOT 1)
    elseif ((BINS EQUAL 6) AND (R EQUAL 15) AND (S EQUAL 11))
        set(MONOT 3)
    elseif ((BINS GREATER_EQUAL 7) AND (R EQUAL 15) AND (S EQUAL 11))
        set(MONOT 5)
    else ()
        math(EXPR MONOT "${S} - 1")
    endif ()
    return(PROPAGATE MONOT)
endfunction()

function(recommend_scaling BINS R S)
    if ((BINS EQUAL 3) AND (R EQUAL 112) AND (S EQUAL 82))
        set(SCALE 12)
    elseif ((BINS EQUAL 3) AND (R EQUAL 329) AND (S EQUAL 240)) # For some specific configurations.
        set(SCALE 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 411) AND (S EQUAL 300))
        set(SCALE 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 657) AND (S EQUAL 480))
        set(SCALE 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 821) AND (S EQUAL 600))
        set(SCALE 6)
    elseif ((BINS EQUAL 3) AND (R EQUAL 985) AND (S EQUAL 720))
        set(SCALE 6)
    elseif ((BINS EQUAL 3)) # Default on 3 bins.
        set(SCALE 6)
        # 4 bins:
    elseif ((BINS EQUAL 4) AND (R EQUAL 19) AND (S EQUAL 14))
        set(SCALE 6)
    elseif ((BINS EQUAL 4))
	set(SCALE 12) # Potentially set 12 here later.
    elseif ((BINS LESS_EQUAL 7) AND (R EQUAL 19) AND (S EQUAL 14))
        set(SCALE 6)
    elseif ((BINS GREATER_EQUAL 8) AND (IBINS LESS_EQUAL 9) AND (R EQUAL 19) AND (S EQUAL 14))
        set(SCALE 6)
    elseif ((BINS GREATER_EQUAL 10) AND (R EQUAL 19) AND (S EQUAL 14))
        set(SCALE 3)
    else ()
        set(SCALE 3)
    endif ()
    return(PROPAGATE SCALE)
endfunction()
